server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

  servlet:
    context-path: /api

logging:
  level:
    root: warn
    org:
      springframework:
        web: debug
        data:
          rest: debug

spring:
  application:
    name: Gateway

  jackson:
    time-zone: "America/Guatemala"
    mapper:
      "[ACCEPT_CASE_INSENSITIVE_ENUMS]": true

security:
  rsa:
    public-key: classpath:certs/public-key.pem

route:
  services:
    auth:
      url: ${GATEKEEPER_URL:http://gatekeeper:8001/}

    employee:
      url: ${HR_URL:http://hr:8002/}

    patient:
      url: ${WARD_URL:http://ward:8003/}

    pharmacy:
      url: ${RX_URL:http://rx:8004/}

springdoc:
  swagger-ui:
    urls:
      - url: /v3/api-docs
        name: API Gateway Service

      - url: /gatekeeper/v3/api-docs
        name: Auth Service

      - url: /hr/v3/api-docs
        name: Employee Service

      - url: /ward/v3/api-docs
        name: Patient Service

      - url: /rx/v3/api-docs
        name: Pharmacy Service