server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

  servlet:
    context-path: /api

logging:
  level:
    root: warn
    org:
      springframework:
        web: debug
        data:
          rest: debug

spring:
  application:
    name: gateway-service

  jackson:
    time-zone: "America/Guatemala"
    mapper:
      "[ACCEPT_CASE_INSENSITIVE_ENUMS]": true

security:
  rsa:
    public-key: classpath:certs/public-key.pem

route:
  services:
    auth-identity:
      url: ${AUTH_IDENTITY_URL:http://localhost:8081/}


springdoc:
  swagger-ui:
    urls:
      - url: /v3/api-docs
        name: API Gateway Service

      - url: /auth-identity/v3/api-docs
        name: Auth Service

