server:
  port: ${PORT:8080}
  error:
    include-message: always
    include-binding-errors: always

  servlet:
    context-path: /api

logging:
  level:
    root: warn
    org:
      springframework:
        web: debug
        data:
          rest: debug

spring:
  application:
    name: gateway-service

  jackson:
    time-zone: "America/Guatemala"
    mapper:
      "[ACCEPT_CASE_INSENSITIVE_ENUMS]": true

security:
  rsa:
    public-key: classpath:certs/public-key.pem

route:
  services:
    auth-identity:
      url: ${AUTH_IDENTITY_URL:http://localhost:8081/}
    hotel:
      url: ${HOTEL_URL:http://localhost:8082/}
    restaurant:
      url: ${RESTAURANT_URL:http://localhost:8084/}
    promotion:
        url: ${PROMOTION_URL:http://localhost:8085/}
    reviews:
      url: ${REVIEWS_URL:http://localhost:8086/}
    finance:
      url: ${FINANCE_URL:http://localhost:8087/}


springdoc:
  swagger-ui:
    urls:
      - url: /v3/api-docs
        name: API Gateway Service

      - url: /auth-identity/v3/api-docs
        name: Auth Service

      - url: /hotel/v3/api-docs
        name: hotel Service

      - url: /restaurant/v3/api-docs
        name: restaurant Service

      - url: /promotion/v3/api-docs
        name: promotion Service

      - url: /reviews/v3/api-docs
        name: reviews Service

      - url: /finance/v3/api-docs
        name: finance Service
